---
# Every time I make changes to this file I need to restart Jekyll to see it take effect!

description: This is the personal website of Yoko Sakao Ohama.
email: ysohama+site@gmail.com
markdown: kramdown
permalink: /:year-:month-:day-:title:output_ext
timezone: America/New_York
title: yoko.cool

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/